import {fonts} from "@/app/fonts";
import "./globals.css";
import {cn} from "@/lib/utils";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" className="dark">
        <body
            className={cn("min-h-screen bg-gradient-to-r from-[#4C3B63] to-[#0F0D0D] font-sans antialiased", fonts.map((font) => font.variable).join(" "),)}>
        {children}
        </body>
        </html>
);
}
